### ISSUE TITLE
How to add "left arrow key or Right arrow key"

### ISSUE THREAD

**Issue by thetejasmagade** [rogeriotaques/vue-hotkeys-rt#19]
Hey @rogeriotaques,
How to add Arrow keys?

**Comment by rogeriotaques** [comment]
Hey @thetejasmagade! 

Sorry for the late reply!

I'm afraid you might not be able to handle the arrow keys with the current implementation! Sorry.
It might be possible with a minor change in the code, tho. 🤔

**Comment by thetejasmagade** [comment]
No, @rogeriotaques don't worry about it.

**Comment by rogeriotaques** [comment]
Great job, @thetejasmagade! 🚀 
Thank you for your contribution. 🙇‍♂️
