### ISSUE TITLE
Do, you think we should have to improve our website

### ISSUE THREAD

**Issue by thetejasmagade** [rogeriotaques/vue-hotkeys-rt#21]
Hey @rogeriotaques my friend Do you think we should have to improve  `vue-hotkeys-rt` demo website by making it stylish or adding proper docs to it?
If yes then I can do it if you don't mind.

**Comment by rogeriotaques** [comment]
Yeah, it sounds like a terrific idea, @thetejasmagade! 🤩  
I would love to see some cool demo pages for this component! 
Go for it and I'll be more than happy to merge it into master. 🤗

**Comment by thetejasmagade** [comment]
Yeah! I would start to work on it. 😊
and Can you please update [https://www.npmjs.com/package/vue-hotkeys-rt]( https://www.npmjs.com/package/vue-hotkeys-rt) it because there are lots of info is missing like there is no link of demo page and image is also not showing.

**Comment by rogeriotaques** [comment]
> Yeah! I would start to work on it. 😊

Sounds great! Thank you.

> and Can you please update [npmjs.com/package/vue-hotkeys-rt](https://www.npmjs.com/package/vue-hotkeys-rt) ...

Sure thing. Will do it ASAP and let you know when it's done.

**Comment by rogeriotaques** [comment]
@thetejasmagade 👋, readme and NPM version updated. 
Thank you for the heads-up!

**Comment by thetejasmagade** [comment]
Also, Can you please move website into netlify or vercel? It will be better if you can do it.
